server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: fastfood
  datasource:
    url: "jdbc:mysql://localhost:3306/fast_food_management"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: pcE5qxJCj55jPBsXL1GvZ8C8xFrKuDd8
  access-token-expiration: 30000
  refresh-token-expiration: 604800000
